stages:
  - build
  - test
  - deploy

# before_script:
#   - |
#     cat > .env << EOF
#     CONFIG_PATH=$CONFIG_PATH
#     SERVER_PORT=$SERVER_PORT
#     EOF

build-job:
  stage: build
  script:
    - docker build -t aloh-image .

test-job:
  stage: test
  script:
    - echo "testing..."
    - sleep 10s

deploy-job:
  stage: deploy 
  script:
    - mkdir -p ./certs
    - cp "$QUIC_CERT_FILE" ./certs/server.crt
    - cp "$QUIC_KEY_FILE" ./certs/server.key
    - chmod 600 ./certs/server.key
    - |
      cat > .env << EOF
      CONFIG_PATH=$CONFIG_PATH
      SERVER_PORT=$SERVER_PORT
      EOF
    - docker-compose rm -s -f aloh || true
    - docker-compose logs aloh