stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t aloh-image .

test-job:
  stage: test
  script:
    - echo "testing..."
    - sleep 10s

deploy-job:
  stage: deploy 
  script:
    - mkdir -p ./certs
    - cp "$QUIC_CERT_FILE" ./certs/server.crt
    - cp "$QUIC_KEY_FILE" ./certs/server.key
    - chmod 600 ./certs/server.key
    - cp $ENV_FILE .env
    - ls -a
    - docker-compose rm -s -f aloh || true
    - docker-compose -f docker-compose.yaml up -d --force-recreate aloh
    - R_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' alohssh)
    - if [ "$R_EXIT_CODE" -ne 0 ]; then
        echo "container failed with exit code $R_EXIT_CODE";
        docker logs aloh;
        exit 1;
      fi
    - sleep 5
    - docker-compose logs aloh