services:
  aloh:
    build: .
    container_name: aloh
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/tcp" 
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    volumes:
      - ../certs:/etc/certs:ro 