services:
  aloh:
    # build: .
    image: aloh-image:latest
    container_name: aloh
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/tcp" 
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    volumes:
      - ./certs:/etc/certs:ro 